
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaModelo
{

using System;
    using System.Collections.Generic;
    
public partial class Habitos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Habitos()
    {

        this.Consultas = new HashSet<Consultas>();

    }


    public int idhabito { get; set; }

    public string bricomania { get; set; }

    public string contrac_musc { get; set; }

    public string habi_mordi { get; set; }

    public string resp_bucal { get; set; }

    public string chupa_labios { get; set; }

    public string chupa_lengua { get; set; }

    public string chupa_dedos { get; set; }

    public Nullable<int> frecuencia { get; set; }

    public string alimentacion { get; set; }

    public int paciente { get; set; }



    public virtual Pacientes Pacientes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Consultas> Consultas { get; set; }

}

}
