
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CapaModelo
{

using System;
    using System.Collections.Generic;
    
public partial class Parodontograma
{

    public int idparadonto { get; set; }

    public string d11 { get; set; }

    public string d12 { get; set; }

    public string d13 { get; set; }

    public string d14 { get; set; }

    public string d15 { get; set; }

    public string d16 { get; set; }

    public string d17 { get; set; }

    public string d18 { get; set; }

    public string d21 { get; set; }

    public string d22 { get; set; }

    public string d23 { get; set; }

    public string d24 { get; set; }

    public string d25 { get; set; }

    public string d26 { get; set; }

    public string d27 { get; set; }

    public string d28 { get; set; }

    public string d31 { get; set; }

    public string d32 { get; set; }

    public string d33 { get; set; }

    public string d34 { get; set; }

    public string d35 { get; set; }

    public string d36 { get; set; }

    public string d37 { get; set; }

    public string d38 { get; set; }

    public string d41 { get; set; }

    public string d42 { get; set; }

    public string d43 { get; set; }

    public string d44 { get; set; }

    public string d45 { get; set; }

    public string d46 { get; set; }

    public string d47 { get; set; }

    public string d48 { get; set; }

    public int paciente { get; set; }



    public virtual Pacientes Pacientes { get; set; }

}

}
