//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tejidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tejidos()
        {
            this.Consultas = new HashSet<Consultas>();
        }
    
        public int idtejidos { get; set; }
        public string duros { get; set; }
        public string rx { get; set; }
        public string encia { get; set; }
        public string inser_epi { get; set; }
        public string lengua { get; set; }
        public string pulpa { get; set; }
        public string velo { get; set; }
        public string carrillos { get; set; }
        public string sob_mord { get; set; }
        public string mordi_abier { get; set; }
        public string desg_bru { get; set; }
        public string anoclusion { get; set; }
        public int paciente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultas> Consultas { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
