//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adicional
    {
        public int idadicional { get; set; }
        public string rech_apri { get; set; }
        public string trat_encias { get; set; }
        public string ori_bucal { get; set; }
        public string ciru_encias { get; set; }
        public string hemorragias { get; set; }
        public int veces_cepillado { get; set; }
        public string tipo_cepillo { get; set; }
        public int paciente { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
    }
}
