//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacientes()
        {
            this.Adicional = new HashSet<Adicional>();
            this.Antecendentes = new HashSet<Antecendentes>();
            this.Habitos = new HashSet<Habitos>();
            this.Tejidos = new HashSet<Tejidos>();
            this.Tratamiento = new HashSet<Tratamiento>();
            this.Consultas = new HashSet<Consultas>();
            this.Parodontograma = new HashSet<Parodontograma>();
        }
    
        public int idpaciente { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string domicilio { get; set; }
        public Nullable<long> telefono { get; set; }
        public Nullable<long> celular { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string apa_resp { get; set; }
        public string apa_cardi { get; set; }
        public string apa_diges { get; set; }
        public string sis_nerv { get; set; }
        public string prob_goagu { get; set; }
        public string desmayos { get; set; }
        public string verti_mareo { get; set; }
        public string diabetes { get; set; }
        public string tiroides { get; set; }
        public string fie_reu { get; set; }
        public string hipertension { get; set; }
        public string otro_antecedente { get; set; }
        public int odontologo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adicional> Adicional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antecendentes> Antecendentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habitos> Habitos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tejidos> Tejidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamiento> Tratamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultas> Consultas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parodontograma> Parodontograma { get; set; }
    }
}
